### ISSUE TITLE
No source included.

### ISSUE THREAD

**Issue by nikmartin** [casualwriter/powerpage#4]
The source folder is this repository contains no source code. Do you actually expect someone to download a random .exe  and run it in 2021?

**Comment by casualwriter** [comment]
powerpage.pbl is the source of powerbuilder. I will also export pb entries to readable text file for review. 

To compile from source, please add target powerpage.pbt in powerbuilder 10.5, and compile "p_powerpage" in powerpage.pbl.

**Comment by nikmartin** [comment]
Powerbuilder? May I ask why powerbuilder is your preferred environment in 2021?

**Comment by casualwriter** [comment]
yes, quite outdate like me.  
powerbuilder is good, and I happen good in powerbuilder. Though it didnot get well evolution since pb5 (1996), it is a good dev tool still.

well, this project show a manner to interact with web-engine to make use of WEB-UI and js libraries. Any dev tool support MS webbrowser control with DB connectivity can make similar utility like powerpage.exe (e.g. .NET, python, c#, ...)
